// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olfjzbvqemqthfmpaloz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sZmp6YnZxZW1xdGhmbXBhbG96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1Mjg1MjUsImV4cCI6MjA2MTEwNDUyNX0.iGJKTNXY8oQDQ4MQanK4E0esAet5T1vbQukpONUvT60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);